name: Translation
description: Provide a translation for in-game strings.
title: 'Translation: '
labels:
  - enhancement
  - translation
assignees:
  - p3lim
body:
  - type: dropdown
    id: locale
    attributes:
      label: Which locale are these translations for?
      options:
        - deDE (German)
        - esES (Spanish, Spain)
        - esMX (Spanish, Mexico)
        - frFR (French)
        - itIT (Italian)
        - koKR (Korean)
        - ptBR (Portuguese, Brazil)
        - ruRU (Russian)
        - zhCN (Chinese, Simplified, PRC)
        - zhTW (Chinese, Traditional, Taiwan)
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        Please translate each sentence below into the fields next to them.  
        It is not required to translate all of them.

        ---
# the rest is a list of strings to translate
  - type: input
    attributes:
      label: '"Map pin scale"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"The scale of world quest pins on the current map"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Overview pin scale"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"The scale of world quest pins on a parent/continent map"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Pin size zoom factor"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"How much extra scale to apply when map is zoomed"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Hold key to hide"'
      description: Used in the settings
      placeholder: Translation here
  - type: input
    attributes:
      label: '"Hold this key to temporarily hide all world quests"'
      description: Used in the settings
      placeholder: Translation here
